version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y git python3 python3-pip apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt update
            apt install -y docker-ce docker-ce-cli containerd.io
      - checkout

      - run:
          name: Python style checks
          command: |
            pip3 install $(cat requirements.txt | grep -e flake8 -e black -e awscli)
            sh ./codetools/check_py_style.sh
          name: Get branch env variable
          command: |
            echo 'export DOCKER_BUILD_ARGS="--build-arg current_branch=${CIRCLE_BRANCH}"' >> $BASH_ENV

      - setup_remote_docker
      - run:
          name: Deploy Github key
          command: |
            echo ${MCDEPLOY_KEY_B64} | base64 -d > docker/mcdeploy.key
            chmod 400 docker/mcdeploy.key

      - run:
          name: Build docker containers
          command: make -C docker build

      - run:
          name: Python unit tests
          command: docker run --entrypoint=/minecraft/python/craftassist/test.sh craftassist

      - run:
          name: Python style checks
          command: |
            pip3 install $(cat requirements.txt | grep -e flake8 -e black -e awscli)
            sh ./codetools/check_and_fix_py_style.sh

      - run:
          name: Push versioned docker containers
          command: |
            docker/login.sh
            make -C docker push-versioned
