/**
 *
 * @license
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 */

/**
 * @fileoverview This file contains the definition and code generator for the custom block used by the template generator.
 */

import * as Blockly from "blockly/core";
import "blockly/javascript";
import saveBlockCallback from "./rightClickCallbacks/saveBlockCallback";
import tagBlockCallback from "./rightClickCallbacks/tagBlockCallback";
import customInit from "./customInit";
/**
 *
 * A custom block has a next connection, and a name field.
 * The name field is the name of the Template object that the block
 * represents.
 */

Blockly.Blocks["parent"] = {
  init: function () {
    this.appendValueInput("next")
      .setCheck(null)
      .appendField(new Blockly.FieldTextInput("Parent"), "parent");

    this.setInputsInline(false);
    this.setColour(270);
    this.setTooltip("");
    this.setHelpUrl("");
    this.setOutput(true, null);

    customInit(this);
  },
};

// The code generated by a custom block is a function of its name.

Blockly.JavaScript["parent"] = function (block) {
  var code = block.getFieldValue("parent");

  return [JSON.stringify(code), Blockly.JavaScript.ORDER_ATOMIC];
};
